### ISSUE TITLE
Builds broken, no releases since April

### ISSUE THREAD

**Issue by scy** [geoacumen/python-geoacumen#1]
Hey, just a quick heads-up that there has not been a successful build since April 30, because the automated builds are broken.

As far as I can see, the issue is an incompatibility between twine and newer versions of urllib3. Twine has since fixed the issue by releasing 4.0.2, but since this project’s `requirements.txt` has it pinned to 3.2.0, we are not receiving the fix. See https://github.com/pypa/twine/issues/997 for details.

Would you mind checking whether using a more up-to-date version of twine fixes the builds? Thanks!

**Comment by ColdHeat** [comment]
Thank you for reporting this I will take a look.

**Comment by ColdHeat** [comment]
Should be working again. See https://pypi.org/project/python-geoacumen/2023.10.26/. Thanks again!
